/* ============================================================
   IFMSA · Khyber Medical College
   Standing committee data + planned projects for the year +
   the stories behind them (highlights).
   Consumed by index.html (committee project lists),
   projects.html (single-project detail view) and
   highlights.html (highlights page).
   ============================================================ */

window.IFMSA_DATA = {
  year: "2026",

  committees: {
    scope: { slug: "scope",  acronym: "SCOPE", name: "Professional Exchange",          color: "#0180C8", accent: "#0180C8", logo: "assets/sc-SCOPE.png" },
    scom:  { slug: "scom",   acronym: "SCOME", name: "Medical Education",               color: "#e6edf3", accent: "#0969da", logo: "assets/sc-SCOME.png" },
    scora: { slug: "scora",  acronym: "SCORA", name: "Sexual & Reproductive Health",   color: "#B2222A", accent: "#B2222A", logo: "assets/sc-SCORA.png" },
    scoph: { slug: "scoph",  acronym: "SCOPH", name: "Public Health",                  color: "#F47D3C", accent: "#F47D3C", logo: "assets/sc-SCOPH.png" },
    scorp: { slug: "scorp",  acronym: "SCORP", name: "Human Rights & Peace",          color: "#5F913F", accent: "#5F913F", logo: "assets/sc-SCORP.png" },
    score: { slug: "score",  acronym: "SCORE", name: "Research Exchange",            color: "#2F4A9B", accent: "#2F4A9B", logo: "assets/sc-SCORE.png" },
  },

  // Meet the Executive Board page — one object per member.
  execBoard: [
    { name: "Ahmad Raza",        role: "President",                    photo: "", quote: "A local council works when every member feels they built it. My job is to make sure no one here is just watching." },
    { name: "Fatima Noor",       role: "Vice-President",               photo: "", quote: "I joined IFMSA for one project and stayed for the people. Everything on this board starts with saying yes to a student somewhere." },
    { name: "Hamza Malik",       role: "Secretary General",            photo: "", quote: "Behind every great event is paperwork no one sees. I keep the council honest, organised, and always one step ahead." },
    { name: "Zainab Akhtar",     role: "Treasurer & Finance Officer",  photo: "", quote: "Good ideas deserve good budgets. I make sure every rupee we raise goes back into projects our members actually feel." },
    { name: "Bilal Shah",        role: "Local Officer — SCOPE",        photo: "", quote: "Exchanges taught me that medicine is a conversation, not a classroom. I want every KMC student to have a seat in it." },
    { name: "Ayesha Kanwal",     role: "Local Officer — SCOME",        photo: "", quote: "We learn medicine best when we teach each other. SCOME is where the lecture hall becomes the classroom." },
    { name: "Usman Tariq",       role: "Local Officer — SCORA",        photo: "", quote: "Health is a right, including sexual and reproductive health. Advocacy here starts with honest conversations on campus." },
    { name: "Mahnoor Khan",      role: "Local Officer — SCOPH",        photo: "", quote: "Public health is the silent backbone of good medicine. Our campaigns turn knowledge into care for the people around us." },
    { name: "Hassan Qureshi",    role: "Local Officer — SCORP",        photo: "", quote: "Human rights and peace are not sidelines in health — they are its foundation. We stand where patients cannot." },
    { name: "Iqra Yousaf",       role: "Local Officer — SCORE",        photo: "", quote: "Research is how medicine grows. SCORE is how students get their first taste of asking a question worth answering." }
  ],

  // Where they are now — alumni of the council.
  alumni: [
    {
      name: "Dr. Sana Yousafzai", cohort: "Batch of 2018", track: "Clinical",
      role_now: "Resident — Internal Medicine", location: "Peshawar, Pakistan",
      specialty: "Internal Medicine", committees: "SCOPE, SCORE", photo: "",
      quote: "Her first SCOPE rotation was in Türkiye. Today she clerks at a teaching hospital in Peshawar — and still signs outbound students before every summer exchange.",
      story: [
        "Sana left KMC with one exchange on her CV and a second one booked. Her SCOPE rotation in Türkiye convinced her that a ward is a ward everywhere, and that the doctor inside you travels with you.",
        "She returned the favour: for five years she ran the exchange committee's pre-departure sessions, and to this day a new cohort of outbound students sit through her briefing before flying.",
        "Now a resident in internal medicine at a Peshawar teaching hospital, she credits IFMSA for teaching her to introduce herself to a patient in any language and to treat a colleague on the far side of the planet as one.",
        "![Sana on rounds](https://picsum.photos/seed/al-sana-1/1200/900)"
      ],
      links: { linkedin: "https://www.linkedin.com/" },
      featured: true, sort_order: 0
    },
    {
      name: "Dr. Ali Haider", cohort: "Batch of 2016", track: "Research",
      role_now: "PhD Candidate — Global Health", location: "London, UK",
      specialty: "Public Health Research", committees: "SCORP, SCOPH", photo: "",
      quote: "Left a ward job to ask why health systems fail the people they exist for. Now a PhD candidate in London.",
      story: [
        "Ali walked out of his final year with more questions than answers — and SCORP had taught him to ask them out loud. After a few years on the wards he traded the stethoscope for a spreadsheet and started a PhD in global health.",
        "His thesis follows the exact communities SCOPH's screening Saturdays used to serve — the referral chain between a blood-pressure reading and a prescription.",
        "He still calls KMC his laboratory: the campus campaigns taught him more about access than any textbook.",
        "![Ali in his research office](https://picsum.photos/seed/al-ali-1/1200/900)"
      ],
      links: { linkedin: "https://www.linkedin.com/", twitter: "https://twitter.com/" },
      featured: false, sort_order: 1
    },
    {
      name: "Dr. Ayesha Begum", cohort: "Batch of 2019", track: "Clinical",
      role_now: "Resident — Pediatrics", location: "Islamabad, Pakistan",
      specialty: "Pediatrics", committees: "SCOPH", photo: "",
      quote: "SCOPH taught her to talk to parents, not just patients. Now a pediatrics resident in the capital.",
      story: [
        "Ayesha's first talk was to a classroom of children holding habit cards, courtesy of SCOPH's school outreach. She was terrified. By her third year she was the one training the new volunteers.",
        "That early practice is now her whole job: every consultation with a worried parent is a small outreach clinic. She is a pediatrics resident in Islamabad and still runs a school health day every term when the roster allows.",
        "Her advice to a first-year: take the outreach project, not the easy seat. The bedside will teach itself; the classroom teaches you to be heard.",
        "![Ayesha in the children's ward](https://picsum.photos/seed/al-ayesha-1/1200/900)"
      ],
      links: { linkedin: "https://www.linkedin.com/" },
      featured: false, sort_order: 2
    },
    {
      name: "Dr. Hamza Gondal", cohort: "Batch of 2015", track: "Beyond Medicine",
      role_now: "Founder — HealthTech Startup", location: "Karachi, Pakistan",
      specialty: "MedTech / Entrepreneurship", committees: "SCOME", photo: "",
      quote: "SCOME's peer-teaching series showed him he could build a room and fill it. Now he builds products for clinics.",
      story: [
        "Hamza never intended to leave clinical medicine — he intended to build tools for the doctors who stayed. SCOME's Tutor Academy gave him his first taste of designing a session people actually turned up to; a decade later he designs software instead.",
        "His startup builds clinic management tools for small practices in Pakistan — the exact kind of practice where his classmates started their careers.",
        "He still uses the feedback loops SCOME taught him: ship something, watch how people react, rebuild.",
        "![Hamza demoing his product](https://picsum.photos/seed/al-hamza-1/1200/900)"
      ],
      links: { linkedin: "https://www.linkedin.com/", twitter: "https://twitter.com/" },
      featured: false, sort_order: 3
    },
    {
      name: "Dr. Zainab Qureshi", cohort: "Batch of 2017", track: "Public Health",
      role_now: "District Health Officer", location: "Khyber, Pakistan",
      specialty: "District Health", committees: "SCORP, SCOPH", photo: "",
      quote: "Led the Humanity Trucks convoy in her final year. Now she runs a district health office where relief plans get made.",
      story: [
        "In her final year Zainab stood at the front of the Humanity Trucks convoy, audited every blanket, and wrote the report that made the district trust the council.",
        "She has spent the years since scaling that single convoy into a career: as a district health officer she now draws the plans that move supplies, staff and vaccines to the places the road ends.",
        "She quotes her own first-year self often: health is a human right. The difference is she now signs the requisition forms.",
        "![Zainab at a district planning meeting](https://picsum.photos/seed/al-zainab-1/1200/900)"
      ],
      links: { linkedin: "https://www.linkedin.com/" },
      featured: true, sort_order: 4
    },
    {
      name: "Dr. Omar Farooq", cohort: "Batch of 2014", track: "Clinical",
      role_now: "Consultant — Cardiology", location: "Rawalpindi, Pakistan",
      specialty: "Cardiology", committees: "SCOPE, SCORE", photo: "",
      quote: "One SCORE summer in a London lab turned into a career in cardiology and an annual lecture for KMC students.",
      story: [
        "Omar's SCORE summer research placement in London ended with his name on an abstract — and a conviction that a clinical question is the best research question there is.",
        "He trained into cardiology and now consults in Rawalpindi, but returns to KMC most years to deliver the research hour the committee still books him for.",
        "His standing invitation stands: any student who wants a poster, an abstract or a plain honest read of their data can send it to him. He answers."
      ],
      links: { linkedin: "https://www.linkedin.com/", email: "president.kmclc.ifmsapakistan@gmail.com" },
      featured: false, sort_order: 5
    },
    {
      name: "Dr. Mahnoor Aslam", cohort: "Batch of 2020", track: "Research",
      role_now: "Research Fellow", location: "Boston, USA",
      specialty: "Epidemiology", committees: "SCORE", photo: "",
      quote: "SCORE's mentorship pairing gave her a first project; an NIH fellowship gave her the next ten.",
      story: [
        "Mahnoor's first research question was written in a KMC corridor, on the back of a SCORE mentorship signup sheet. The mentor she was paired with stayed with her through the project, the poster and the paper.",
        "She is now an epidemiology research fellow in Boston, working on datasets that would have seemed fictional to her as a student.",
        "She still mentors a KMC student every year — her way of paying forward the pair of hands that once steadied her first sample size calculation."
      ],
      links: { linkedin: "https://www.linkedin.com/", twitter: "https://twitter.com/" },
      featured: false, sort_order: 6
    },
    {
      name: "Dr. Bilal Khattak", cohort: "Batch of 2013", track: "Leadership",
      role_now: "National President — IFMSA-Pakistan", location: "Islamabad, Pakistan",
      specialty: "Policy / Federation", committees: "SCOPE", photo: "",
      quote: "From KMC Local Officer to leading the federation: the longest journey on this page, started with a single committee desk.",
      story: [
        "Bilal's first IFMSA role was a desk in the KMC SCOPE office. He was the Local Officer who matched the first exchange cohort, then the delegate, then the national team.",
        "A decade later he leads IFMSA-Pakistan, representing Pakistani medical students to the federation's global assembly.",
        "His message to KMC is unchanged from his first ever speech: the council is a ladder, and it is built to be climbed by every student who steps on it."
      ],
      links: { linkedin: "https://www.linkedin.com/" },
      featured: true, sort_order: 7
    },
    {
      name: "Dr. Sarah Ahmed", cohort: "Batch of 2021", track: "Beyond Medicine",
      role_now: "Medical Writer & Educator", location: "Lahore, Pakistan",
      specialty: "Health Communication", committees: "SCOME", photo: "",
      quote: "Writes the teaching material SCOME now uses — proof that a peer-teaching series can outlive its tutors.",
      story: [
        "Sarah wrote her first lesson plan for the Peer Teaching Series and never really stopped writing. What began as a student's slide deck became a career in medical communication.",
        "She now works as a medical writer and educator, producing curricula and patient material that clinics actually use — including the updated pack SCOME distributes on campus.",
        "She likes to tell students that the only skill you keep forever is the one you use to teach someone else."
      ],
      links: { linkedin: "https://www.linkedin.com/", email: "president.kmclc.ifmsapakistan@gmail.com" },
      featured: false, sort_order: 8
    }
  ],

  projects: [
    /* ---------------- SCOPE · Professional Exchange ---------------- */
    {
      id: "scope-2026-summer-exchange",
      committee: "scope",
      title: "Summer Exchange 2026",
      type: "Exchange",
      status: "Applications open",
      timeframe: "May – Aug 2026",
      theme: "Outbound · IFMSA Exchanges",
      summary: "Four-week clinical rotations in teaching hospitals across twelve exchange partner countries.",
      about: [
        "Every summer SCOPE wakes the council up and sends it abroad. Selected students match to a host committee, then live, learn and clerk beside peers in hospitals they would otherwise never step into — from operating theatres in Türkiye to rural clinics in Colombia.",
        "Outbound preparation runs through the spring: visa clinics, insurance and immunisation checks, safety briefings and a buddy-pairing system so no one crosses a border alone. Every returning student debriefs with the exchange committee, so the next cohort starts a step ahead.",
        "![Rotations at partner hospitals](https://picsum.photos/seed/scope-hospital-1/1200/900)",
        "![Wards and ward rounds](https://picsum.photos/seed/scope-hospital-2/1200/900)",
      ],
      goals: [
        "Place 25 KMC students in host hospitals across full rounds.",
        "Run four pre-departure preparation sessions in the spring term.",
        "Reach 100% returning-student debrief completion.",
      ],
    },
    {
      id: "scope-2026-winter-exchange",
      committee: "scope",
      title: "Winter Exchange 2026/27",
      type: "Exchange",
      status: "Planned",
      timeframe: "Jan – Mar 2027",
      theme: "Outbound · Internal medicine",
      summary: "A shorter winter-round rotation focused on internal medicine and emergency blocks.",
      about: [
        "A winter round for students who could not travel in summer, or who want a second rotation before licensure. Placements are denser and shorter, engineered around the winter academic break — quieter hospitals mean more hands-on time at the bedside.",
        "Selection mirrors the summer round: academic standing, language readiness and a personal statement. The call for applications opens in September and the hospital list locks by December.",
      ],
      goals: [
        "Offer at least 12 winter placements.",
        "Publish the call for applications in September 2026.",
        "Lock all host choices by December 2026.",
      ],
    },
    {
      id: "scope-2026-pre-departure-bootcamp",
      committee: "scope",
      title: "Pre-Departure Bootcamp",
      type: "Workshop",
      status: "Planned",
      timeframe: "Mar 2026",
      theme: "Preparation · Safety",
      summary: "A half-day clinic on paperwork, travel safety, insurance and clinical etiquette before flights.",
      about: [
        "The nine deadliest words in exchange prep are 'I will handle it at the hospital'. This bootcamp exists so nobody ever says them. We walk the entire checklist — insurance, visas, vaccination records, housing, bedside behaviour and the exact documents a host SCOPE will ask for.",
        "Alumni who already completed a round run mock scenarios and answer the questions only returning students know to ask: what if a flight is cancelled, what if the duty shift runs late, who do you call at 3 a.m.? A 24/7 national duty officer is on call for every exchange student.",
      ],
      goals: [
        "Complete all 100% of selected summer students through the bootcamp.",
        "Issue the exchange safety handbook to every attendee.",
      ],
    },
    {
      id: "scope-2026-inbound-hosting",
      committee: "scope",
      title: "Inbound Hosting Programme",
      type: "Hosting",
      status: "Open",
      timeframe: "All year",
      theme: "Inbound · Friendship",
      summary: "Hosting international students on exchange in Peshawar — from airport pickup to ward rotation.",
      about: [
        "Not all exchange energy flows outward. The council opens KMC's doors to inbound students from SCOPE committees worldwide. They rotate through the clinical departments while experiencing the city, our wards and our teaching.",
        "Hosting needs a changing cast of volunteers: airport pickups, weekend cultural tours, guided hospital navigation and a genuine welcome. It is the cheapest international medical conference that ever mistakes you for a colleague, and you get to host.",
      ],
      goals: [
        "Host inbound students from at least eight countries.",
        "Keep a verified 100% host satisfaction rate on the exchange platform.",
      ],
    },
    {
      id: "scope-2026-exchanged-alumni-panel",
      committee: "scope",
      title: "Exchanged & Still Alive: Alumni Panel",
      type: "Event",
      status: "Planned",
      timeframe: "Oct 2026",
      theme: "Community · Retrospective",
      summary: "Returning students share real case stories, budgets and lessons with the whole council.",
      about: [
        "The report-back ritual. Students who just returned from summer exchange take the stage for a public debrief — what surprised them, what teaching-culture collisions happened, and what they wish they had packed.",
        "The panel is the council's living memory: full of warm diagnoses, bad laundry stories and one very specific cautionary tale about a health insurance card that expired mid-flight. Every future applicant must listen once.",
      ],
      goals: [
        "Fill the auditorium with the next season of would-be applicants.",
        "Record and archive the session for the local committee.",
      ],
    },

    /* ---------------- SCOME · Medical Education ---------------- */
    {
      id: "scom-2026-peer-teaching-series",
      committee: "scom",
      title: "Peer Teaching Series",
      type: "Educational",
      status: "Accepting tutors",
      timeframe: "Apr – Nov 2026",
      theme: "Peer teaching · Classroom",
      summary: "Senior students lead small-group revision classes for junior classes every week.",
      about: [
        "The spine of SCOME's work: students teaching students. Every week, trained senior students take a small group through a block of anatomy, pharmacology or clinical reasoning — using the fastest teaching format there is: one peer who has already survived that exam.",
        "Tutors sign up in spring, receive a short pedagogy workshop, and are matched to groups by subject compatibility. The series is graded by the students themselves, and the best tutor is crowned at the end-of-year ceremony.",
        "![Small-group revision classes](https://picsum.photos/seed/scom-peerteach-1/1200/900)",
        "![A fellow leading an open lecture](https://picsum.photos/seed/scom-peerteach-2/1200/900)",
      ],
      goals: [
        "Run 20 weekly sessions across 10 subject streams.",
        "Train 40 student tutors through the pedagogy workshop.",
      ],
    },
    {
      id: "scom-2026-skill-bootcamps",
      committee: "scom",
      title: "Clinical & Soft-Skill Bootcamps",
      type: "Workshop",
      status: "Planned",
      timeframe: "Apr & Nov 2026",
      theme: "Skills · Confidence",
      summary: "Weekend bootcamps on suturing, IV access, communication and OSCE nerves.",
      about: [
        "School taught you the seventh cranial nerve; the wards taught you that nobody cares unless you can thread a vein with a steady hand. These bootcamps go both directions — one weekend on hands-on clinical skills in the skills lab, one weekend on bedside communication and surviving an OSCE without disintegrating.",
        "We deliberately mix years, because a third-year calms a second-year better than any lecturer. Spots are capped to keep the instructor-to-student ratio honest, and the signup sheet always fills within an afternoon.",
      ],
      goals: [
        "Cap at 120 students per bootcamp to protect the hands-on ratio.",
        "Cover history-taking, venepuncture, suturing and bad-news stations.",
      ],
    },
    {
      id: "scom-2026-nmed",
      committee: "scom",
      title: "National Medical Education Day",
      type: "Campaign",
      status: "Upcoming",
      timeframe: "21 Oct 2026",
      theme: "Advocacy · Visibility",
      summary: "A council-wide day celebrating students who teach, with a marathon of open classes.",
      about: [
        "On 21 October the council runs dozens of short, open teaching sessions simultaneously — the campus becomes a labyrinth of classes-meets-concert, summed into one loud message: students are teachers too.",
        "The day doubles as a political pitch: a written ask, delivered to the curriculum committee, that peer teaching be recognised with formal credit in the degree. The quiet lecture becomes the official one.",
      ],
      goals: [
        "Hold 30 open micro-sessions in a single day.",
        "Deliver a 500-signature petition to the curriculum committee.",
      ],
    },
    {
      id: "scom-2026-curriculum-forum",
      committee: "scom",
      title: "Student Voice: Curriculum Feedback Forum",
      type: "Policy",
      status: "Planned",
      timeframe: "Sep 2026",
      theme: "Policy · Representation",
      summary: "A structured, chaired forum where students review the syllabus face-to-face with faculty.",
      about: [
        "Students know where teaching hurts before faculty ever does. In a chaired, safe forum, year-delegates present what to keep, what to cut and what to add — and each proposal is ranked by a student vote.",
        "The top ten proposals are written into a published action list and tracked publicly, so students can watch their feedback become a real lecture, a real lighter layer, a real change in how the course is designed.",
      ],
      goals: [
        "Deliver 10 prioritised proposals into the faculty action list.",
        "Bring year-delegates from every class to the forum.",
      ],
    },
    {
      id: "scom-2026-tutor-academy",
      committee: "scom",
      title: "Tutor Academy",
      type: "Programme",
      status: "Beta",
      timeframe: "Ongoing",
      theme: "Capacity building",
      summary: "A mini-fellowship teaching KMC students to design and lead their own sessions.",
      about: [
        "You do not have to be born a teacher to become one. The Academy is a structured cycle of four sessions — design, delivery, feedback and repair — that graduates students able to build a full teaching session from a blank slide.",
        "Fellows first pilot their sessions inside the Peer Teaching Series, then out in the community. The Academy is the quiet incubator for every SCOM-quality lecture that later shows up on campus.",
      ],
      goals: [
        "Graduate 15 fellows per eight-week cycle.",
        "Pilot one original teaching session per graduate.",
      ],
    },

    /* ---------------- SCORA · Sexual & Reproductive Health ---------------- */
    {
      id: "scora-2026-srh-awareness-week",
      committee: "scora",
      title: "Sexual & Reproductive Health Week",
      type: "Campaign",
      status: "Planned",
      timeframe: "May 2026",
      theme: "Awareness · Destigmatisation",
      summary: "A stigma-cracking week of booths, quiet sessions and myth-busting on campus.",
      about: [
        "For one week the taboos open like a clinic door. SCORA takes the campus and turns it into a loud, warm, myth-busting marketplace with a locked box of anonymous questions, a wall of \"answers I was too embarrassed to ask\" and short nurse-led talks — the ones students actually stayed for.",
        "The week ends with a night screening and a livestream for those who cannot be on campus. Everything is confidential, and the health-promotion packs go out free.",
        "![SRH awareness booth](https://picsum.photos/seed/scora-week-1/1200/900)",
        "![Students sharing the myth-busting wall](https://picsum.photos/seed/scora-week-2/1200/900)",
      ],
      goals: [
        "Give away all 600 planned SRH information kits.",
        "Reach more than 1,000 students across the week.",
      ],
    },
    {
      id: "scora-2026-aids-day",
      committee: "scora",
      title: "World AIDS Day — 1 December",
      type: "Campaign",
      status: "Planned",
      timeframe: "1 Dec 2026",
      theme: "Awareness · Stigma",
      summary: "A red-ribbon day of myth-busting, and a quiet evening vigil on campus.",
      about: [
        "One day, one red ribbon: a dated against one of the most stigmatised infections in medicine. SCORA marks it with a corridor of ribbons, a knowledge test that quietly separates myths from facts, and a lamp vigil in the evening for the millions who did not live to see the cure.",
        "Most of the work happens before the day — a thirty-day social series about the vocabulary of stigma, so that by the first of December the campus already knows not just the medicine, but the words.",
      ],
      goals: [
        "Test 300+ students against the myth-busting quiz.",
        "Publish the filmed three-minute student awareness piece.",
      ],
    },
    {
      id: "scora-2026-consent-culture",
      committee: "scora",
      title: "Consent Culture Training",
      type: "Workshop",
      status: "Upcoming",
      timeframe: "Ongoing",
      theme: "Training · Respect",
      summary: "Interactive sessions on affirmative consent, boundaries and bystander roles.",
      about: [
        "Consent is not a lecture — it is peer language. In safe, separate groups, SCORA trains the vocabulary of yes, of boundaries, and of the silence that is always not-ok. The sessions are built around real scenarios, not PowerPoints.",
        "They end with the bystander piece, the closest thing to a fire drill for relationships. Presented with a simply-said scene, a group decides where the line is and what a friend does when one crosses it.",
      ],
      goals: [
        "Train 200+ students across eight sessions.",
        "Leave a facilitator card and a written quick-guide with every session.",
      ],
    },
    {
      id: "scora-2026-breast-awareness",
      committee: "scora",
      title: "Breast Health & Awareness Session",
      type: "Event",
      status: "Planned",
      timeframe: "Oct 2026",
      theme: "Prevention · Women's health",
      summary: "A non-scary conversation about self-examination, risks and when to screen.",
      about: [
        "Two thirds of our students are women, yet almost none were ever told in school how to look after their own breast health. In an October session — calm, informed, gender-appropriate — a clinician leads the demonstration that matters, and the facts about screening.",
        "The day is built to outlast itself: every participant walks out with a plain-language card to keep at home, turning one lecture into a monthly habit.",
      ],
      goals: [
        "Reach 400+ female students with the demonstration.",
        "Distribute the reminder card to every attendee.",
      ],
    },
    {
      id: "scora-2026-peer-support-line",
      committee: "scora",
      title: "Peer Support & Referral Line",
      type: "Support",
      status: "Live",
      timeframe: "All year",
      theme: "Health · Help always on",
      summary: "A confidential student-run line that listens and routes to professionals, without judgement.",
      about: [
        "Not every question wants a poster. Some come only at 1 a.m. The line is student-run among trained volunteers, and every conversation ends in a calm, warm referral — clinic, counsellor or hotline, whichever the caller wants.",
        "No names, no transcripts, no judgement. The SHARE promise holds all year: the answer is silent, the door is open.",
      ],
      goals: [
        "Keep median answer time under 24 hours.",
        "Refer 100% of clinical questions to a relevant professional.",
      ],
    },

    /* ---------------- SCOPH · Public Health ---------------- */
    {
      id: "scoph-2026-community-screenings",
      committee: "scoph",
      title: "Community Health Screening Saturdays",
      type: "Screening",
      status: "Open",
      timeframe: "All year",
      theme: "Community · Access",
      summary: "Monthly weekend camps in Peshawar for blood pressure, sugar and friendly triage.",
      about: [
        "One Saturday a month the council packs up and stands outside a school, mosque or community centre to screen a whole block down Racecourse Road and beyond. Blood pressures, random blood sugars and a calm talk with a student trained to refer.",
        "The impact is durable: each person walks out with a simple card showing what normal is for their age and where to go if the number is red. Nobody is graded; everyone is counted.",
        "![Screening camp at a community centre](https://picsum.photos/seed/scoph-screening-1/1200/900)",
        "![Blood-pressure checks on site](https://picsum.photos/seed/scoph-screening-2/1200/900)",
      ],
      goals: [
        "Screen 2,000 community members over the year.",
        "Complete the follow-up form for every referral made.",
      ],
    },
    {
      id: "scoph-2026-vaccination-drive",
      committee: "scoph",
      title: "Campus Vaccination Drive",
      type: "Campaign",
      status: "Planned",
      timeframe: "Nov 2026",
      theme: "Prevention · Immunity",
      summary: "A pop-up vaccination exercise on campus with a myth-busting parallel wall.",
      about: [
        "Vaccines work best before you need them, so we vaccinate the healthy. SCOPH partners with a local health official to run a pop-up flu camp on campus, appointments and all — both for staff and students.",
        "Beside every queue a myth-busting wall does battle with the annual folklore: side-effect timing, who can wait and who can't, and why the needle hurts less than the disease.",
      ],
      goals: [
        "Vaccinate 1,000 students and staff in one week.",
        "Battle ten common vaccine myths on the wall.",
      ],
    },
    {
      id: "scoph-2026-community-week",
      committee: "scoph",
      title: "Public Health Week",
      type: "Campaign",
      status: "Planned",
      timeframe: "Mar 2026",
      theme: "Awareness · Five disciplines",
      summary: "Five days, five daily disciplines — dengue to hypertension to mental illness.",
      about: [
        "One theme per day, five disciplines in six: dengue (with a standing-water audit), hypertension (a measuring booth), nutrition (a plate that makes sense), tobacco, and the mind being public. The visitors take everything seriously.",
        "The week signs off with the council's own declaration of the public-health minute for the year: students committing to the habit of the campus.",
      ],
      goals: [
        "Host five discipline-days with at least 150 visits each.",
        "Publish one student-written public-health charter for the campus.",
      ],
    },
    {
      id: "scoph-2026-school-outreach",
      committee: "scoph",
      title: "School Health Literacy Outreach",
      type: "Outreach",
      status: "Open",
      timeframe: "All year",
      theme: "Education · Tomorrow",
      summary: "Hands-on, plain-language health lessons in the city's schools every term.",
      about: [
        "The best time to teach a habit is before the class learns the fear. Volunteers run short interactive lessons in Peshawar's schools — how to wash a hand properly, why two sugary drinks is one too many, how to deny a mosquito a puddle.",
        "Every lesson leaves a \"habit card\" for the child to take home, and sometimes a parent at the gate reads it and asks a question. The reach is the point: prevention done where prevention is free.",
      ],
      goals: [
        "Reach 1,500 students across 20 schools.",
        "Give every child a take-home health card.",
      ],
    },
    {
      id: "scoph-2026-environmental-audit",
      committee: "scoph",
      title: "Environmental Health & Climate Audit",
      type: "Project",
      status: "Planned",
      timeframe: "Jun 2026",
      theme: "Planet · One Health",
      summary: "A gentle audit of campus waste, water and air, plus a short list of fixes.",
      about: [
        "A public-health team should also care for the building it trains in. Volunteers walk the campus, count bins, test a doorway's water, and ask the facilities to measure the air — a genuinely mini-EPA for one college block.",
        "The audit is the report; the action is the follow-up. We hang the extra bins, fix the leak the guard has complained about for years, and the best finds go on to the sustainability committee.",
      ],
      goals: [
        "Complete a full environmental audit of the KMC campus.",
        "Land at least five visible fixes from the audit by term four.",
      ],
    },

    /* ---------------- SCORP · Human Rights & Peace ---------------- */
    {
      id: "scorp-2026-refugee-outreach",
      committee: "scorp",
      title: "Refugee & Migrant Health Outreach",
      type: "Outreach",
      status: "Open",
      timeframe: "All year",
      theme: "Rights · Access",
      summary: "Health checks and referrals at the city's registered displaced-people centres.",
      about: [
        "Behind the city's main street some families have crossed a border carrying little more than documents of their trauma. Our volunteers go to the registered settlements to run the same careful checks they would in a campus clinic — plus the referral that their papers keep them from.",
        "Health is a human right is the sentence the project actually lives. The outreach is where our students learn a citizenship that is not only of a hospital, but of a humanity that speaks the sentence.",
        "![Careful checks at a settlement centre](https://picsum.photos/seed/scorp-outreach-1/1200/900)",
        "![A quiet conversation after the exam](https://picsum.photos/seed/scorp-outreach-2/1200/900)",
      ],
      goals: [
        "Hold 12 outreach mornings in the registered settlements.",
        "Connect every diagnosed need to a follow-up person or service.",
      ],
    },
    {
      id: "scorp-2026-peace-week",
      committee: "scorp",
      title: "Peace Week",
      type: "Campaign",
      status: "Planned",
      timeframe: "Sep 2026",
      theme: "Dialogue · Peace",
      summary: "Talks, art and a quiet evening remembering that lasting peace is the best of medicine.",
      about: [
        "Every war is a long and avoidable public-health emergency. Peace Week borrows the campus to talk about medical neutrality, host a panel, screen one intelligent story and end in a lit candle evening where students hang a note of a wish on the tree.",
        "The week is not naive — a doctor's oath is the same over and under. The lectures of the week translate to a simple promise the council adopts aloud.",
      ],
      goals: [
        "Reach 60% of students through the week's events.",
        "Adopt one \"Humanity First\" council statement.",
      ],
    },
    {
      id: "scorp-2026-uhc-day",
      committee: "scorp",
      title: "Universal Health Coverage Day",
      type: "Campaign",
      status: "Planned",
      timeframe: "12 Dec 2026",
      theme: "Fairness · Access",
      summary: "A corridor of practical diagrams — who pays, and who falls out of the system.",
      about: [
        "On 12 December the campus corridor becomes an infographic about coverage: a map of who gets the diabetes medicine and who waits one breath too long. We draw the insurance system as it is — the grid, the gap and the route of a patient from far in the pocket to far from the door.",
        "The day ends with a card for every student: two lines on a human right, and the local phone number where it can be asked.",
      ],
      goals: [
        "Reach one in two students with the coverage chart.",
        "Publish a one-page council call for wider district coverage.",
      ],
    },
    {
      id: "scorp-2026-humanity-trucks",
      committee: "scorp",
      title: "Humanity Trucks: Winter Collection",
      type: "Relief",
      status: "Planned",
      timeframe: "Dec 2026",
      theme: "Solidarity · Cold",
      summary: "A student-run collection drives blankets and medicines to the displaced, in winter.",
      about: [
        "In midwinter, blankets are the difference between a room and a crime of indifference. Students run a coordinated collection — blankets, warm clothes, simple medicines — and move the convoy to registered sites and northern checkpoints.",
        "The collection never leaves a single verified receipt behind; the convoy is the beginning, the arrival is the report, and the trust of the community is the point.",
      ],
      goals: [
        "Deliver 5,000 kg of relief goods to two priority areas.",
        "Publish an audited list of everything carried and delivered.",
      ],
    },
    {
      id: "scorp-2026-film-night",
      committee: "scorp",
      title: "Rights on Reel — Human Rights Film Night",
      type: "Event",
      status: "Planned",
      timeframe: "Aug 2026",
      theme: "Story · Lens",
      summary: "Two short documentaries plus a Q&A on medicine beside the quiet line.",
      about: [
        "Stories do in hidden what legal arguments do in the bright. We screen two short documentaries about health in wars — a hospital at night, a midwife who stayed — and then warm up a Q&A with medics who have watched a war through their own notes.",
        "The night is cinema and curriculum in one: every viewer leaves with the same sentence — health is a human right, and the best medicine a country can deliver is peace.",
      ],
      goals: [
        "Screen two films plus a moderated Q&A.",
        "Reach 200+ students across the evening.",
      ],
    },

    /* ---------------- SCORE · Research Exchange ---------------- */
    {
      id: "score-2026-summer-research",
      committee: "score",
      title: "Summer Research Exchange 2026",
      type: "Exchange",
      status: "Applications open",
      timeframe: "May – Aug 2026",
      theme: "Outbound · Research",
      summary: "Bench and genuinely research placements abroad for the curious-minded.",
      about: [
        "Some students want to spend their summer in a lab instead of on the lido. SCORE placements put candidates into research teams that need a pair of clean hands — molecular biology, epidemiology, guideline writing, or pure cellular curiosity — and pay them forward in mentors, ink and name.",
        "We run the matching as a negotiation: the student's question is picked, the host is studied, and the placement is confirmed before fights. On return, every summer resident gives a ten-minute \"share the lab\" answer to the council.",
        "![Bench time in a host lab](https://picsum.photos/seed/score-lab-1/1200/900)",
        "![A summer resident after data collection](https://picsum.photos/seed/score-lab-2/1200/900)",
      ],
      goals: [
        "Match 8 students — funding considered — to confirmed placements.",
        "Provide the research-passport handbook to every outbound student.",
      ],
    },
    {
      id: "score-2026-methodology-bootcamp",
      committee: "score",
      title: "Research Methodology Bootcamp",
      type: "Workshop",
      status: "Planned",
      timeframe: "Jul 2026",
      theme: "Skills · Rigour",
      summary: "Two days from question to study design — the honest armoury of research.",
      about: [
        "Research stamina is not glamour; it is design. The bootcamp goes battle-hard: from an empty question to a hypothesis, a sample size you did not lie to, a walk-through of study designs, and the plain truth of your first paper.",
        "Anyone who files gets a design worksheet, a reference chart, and the end of the sentence \"I can't do research, I don't have the juice.\"",
      ],
      goals: [
        "Fill 100 participant seats with certificates.",
        "Deliver easy-to-apply checklists for every design skill covered.",
      ],
    },
    {
      id: "score-2026-abstract-clinic",
      committee: "score",
      title: "Abstract & Publishing Clinic",
      type: "Clinic",
      status: "Planned",
      timeframe: "Nov 2026",
      theme: "Publication · Clarity",
      summary: "Small-group walkthroughs turning raw results into a publishable abstract.",
      about: [
        "The bridge between \"I've worked\" and \"I've published\" is a short and good abstract. In small groups we take one completed project and redraw it — a better results table, a proper p-marker, a title that does not need a footnote.",
        "Each group leaves a submission-ready abstract; the best three are championed by the committee — edits, submission, and a dogged hunt for acceptance.",
      ],
      goals: [
        "Produce 15 accepted-grade abstracts.",
        "Guide at least three to a real journal submission within six months.",
      ],
    },
    {
      id: "score-2026-research-hour",
      committee: "score",
      title: "Research Hour",
      type: "Series",
      status: "Planned",
      timeframe: "Monthly",
      theme: "Community · Journal club",
      summary: "A monthly journal club: one compelling paper, one blunt reader.",
      about: [
        "Every month, one paper, one sceptic, one room. The journal club is built to the skeptic, not to be preached to; we ask assumptions, open the methods, and say loudly what the suppression of a sweet idea can cost.",
        "The hour is the most intellectually honest exercise we run. Take the workbook and the following bootcamp feeds quietly on the questions that surface there.",
      ],
      goals: [
        "Run nine sessions in the annual cycle.",
        "Cover the full arc: question, method, statistics sanity-check.",
      ],
    },
    {
      id: "score-2026-mentorship-pairing",
      committee: "score",
      title: "Research Mentorship Programme",
      type: "Programme",
      status: "Open",
      timeframe: "All year",
      theme: "Mentorship · Journey",
      summary: "Student researchers paired with a mentor who steers their first project to a close.",
      about: [
        "A research project is a boat and a mentor is its sail. We pair every student who wants in with a senior — or a researcher — for one project-cycle: from the first question to the last slide of a presentation.",
        "Pairings are matched honestly, almost always twice-blessed; many become collaborations that outlast the project and lead to a poster or a paper.",
      ],
      goals: [
        "Run 30 pairings in the 2026 cohort.",
        "Convert 60% of pairings from a started study into a result.",
      ],
    },
  ],

  /* ---------------- Highlights ----------------
     category: 'away'   → events our members went to
               'campus' → significant on-campus events
               'win'    → wins & recognition
     about: one paragraph per line; a picture is a line in
     the form ![caption](image-url).                 */
  highlights: [
    {
      id: "hl-2026-ga-cape-town",
      category: "away",
      tag: "International Conference",
      title: "IFMSA General Assembly · Cape Town",
      date: "March 2026",
      location: "Cape Town, South Africa",
      committee: "",
      featured: true,
      summary: "Six KMC delegates joined 1,500 medical students from 130+ countries in Cape Town — running workshops, voting on global policy and bringing Peshawar's voice to the floor.",
      about: [
        "For nine days in March the whole movement met in Cape Town: the March Meeting of the IFMSA General Assembly. Our six delegates carried the council across two continents on hand-written proposals, a workshop on peer-led medical education, and a very patient poster about KMC's screening Saturdays.",
        "They came home with more than souvenirs. Two standing committees were awarded seats in IFMSA-Pakistan's national teams — a direct line from a hostel room in Peshawar to the rooms where the federation's health agenda is written.",
        "![Plenary hall at the General Assembly](https://picsum.photos/seed/hl-ga-cape-1/1200/900)",
        "![KMC delegates at the closing ceremony](https://picsum.photos/seed/hl-ga-cape-2/1200/900)",
      ],
    },
    {
      id: "hl-2026-national-ga-islamabad",
      category: "away",
      tag: "National Conference",
      title: "National General Assembly · Pakistan",
      date: "Dec 2026",
      location: "Islamabad, Pakistan",
      committee: "",
      summary: "The council's largest delegation yet travelled to the capital — and two of its members came home with national team roles.",
      about: [
        "The National General Assembly is where every local council in Pakistan meets to set the year ahead. KMC sent its biggest delegation on record — the full executive plus the Local Officers of every standing committee.",
        "Policy positions were debated, regional projects were pledged, and for two students the trip ended with a badge: national team roles under the IFMSA-Pakistan umbrella, representing the council on the national stage for the coming year.",
        "![Delegation photo outside the assembly hall](https://picsum.photos/seed/hl-nga-1/1200/900)",
      ],
    },
    {
      id: "hl-2026-scope-cape-cohort",
      category: "away",
      tag: "Exchange",
      title: "SCOPE Summer Exchange — the biggest cohort yet",
      date: "May – Aug 2026",
      location: "Twelve countries",
      committee: "scope",
      summary: "Twenty-two students matched to clinical rotations in twelve countries — the council's largest outbound cohort on record, from Ankara to Bogotá.",
      about: [
        "Every spring SCOPE wakes the council up and sends it abroad, and this year was different in scale: twenty-two matches, twelve countries, one very busy airport terminal. Rotations ran from operating theatres in Türkiye to rural clinics in Colombia.",
        "The pre-departure bootcamp ran twice to fit the demand, and every returning student debriefed to camera so the report-back lives on for the next cohort. The taster reel at the end of the year was, frankly, unfair to everyone graduating.",
        "![Rotations across partner hospitals](https://picsum.photos/seed/hl-scope-1/1200/900)",
        "![The outbound cohort's group call](https://picsum.photos/seed/hl-scope-2/1200/900)",
      ],
    },
    {
      id: "hl-2026-score-summer-research",
      category: "away",
      tag: "Research Exchange",
      title: "SCORE Summer Research — bench time abroad",
      date: "May – Aug 2026",
      location: "Labs across Europe & Asia",
      committee: "score",
      summary: "Eight students traded Peshawar for research labs across Europe and Asia — and three placements came home as published abstracts.",
      about: [
        "While SCOPE filled the wards, SCORE filled the benches. Eight students matched to research teams abroad — molecular biology, epidemiology and guideline writing — and spent the summer asking questions worth answering.",
        "The return rate was the real headline: three placements turned into accepted abstracts within months, and each summer resident gave the council a ten-minute 'share the lab' talk that convinced at least one second-year to apply immediately.",
        "![Bench time in a host research lab](https://picsum.photos/seed/hl-score-1/1200/900)",
      ],
    },
    {
      id: "hl-2026-scora-srh-week",
      category: "campus",
      tag: "Campus Campaign",
      title: "SRH Week drew a thousand students",
      date: "May 2026",
      location: "KMC Campus, Peshawar",
      committee: "scora",
      summary: "Booths, a myth-busting wall and a locked box of anonymous questions saw record footfall — and 600 information kits walked out the door.",
      about: [
        "For one week the taboos opened like a clinic door. SCORA turned the campus into a loud, warm, myth-busting marketplace with nurse-led talks — the ones students actually stayed for — and a night screening for those who couldn't be on campus.",
        "The numbers spoke: more than a thousand students touched the week, 600 SRH information kits went out free, and the locked box of anonymous questions took a week to read out because nobody expected that many.",
        "![SRH awareness booth on campus](https://picsum.photos/seed/hl-scora-1/1200/900)",
        "![Students at the myth-busting wall](https://picsum.photos/seed/hl-scora-2/1200/900)",
      ],
    },
    {
      id: "hl-2026-scoph-screening-saturdays",
      category: "campus",
      tag: "Community Outreach",
      title: "Screening Saturday reached the whole block",
      date: "All year",
      location: "Racecourse Road, Peshawar",
      committee: "scoph",
      summary: "Monthly weekend camps screened 2,000+ neighbours for blood pressure and sugar — with a calm hand to point the way.",
      about: [
        "One Saturday a month the council packs up and stands outside a school, mosque or community centre to screen a whole block. Blood pressures, random blood sugars, and a calm talk with a student trained to refer.",
        "The year-end total crossed two thousand people screened. Each one walked away with a card showing what normal is for their age and where to go if the number is red — a public-health habit worn one Saturday at a time.",
        "![Screening camp at a community centre](https://picsum.photos/seed/hl-scoph-1/1200/900)",
      ],
    },
    {
      id: "hl-2026-scom-tutor-of-the-year",
      category: "campus",
      tag: "Medical Education",
      title: "Peer Teaching crowned its first Tutor of the Year",
      date: "Oct 2026",
      location: "KMC Campus, Peshawar",
      committee: "scom",
      summary: "Twenty sessions, forty trained tutors, and an end-of-year ceremony that made teaching the campus's favourite skill.",
      about: [
        "The Peer Teaching Series ran twenty weekly sessions across ten subject streams, taught entirely by students who had just survived the exam themselves — the fastest teaching format in medicine.",
        "Forty tutors were trained through the pedagogy workshop, and at the end-of-year ceremony the series crowned its first Tutor of the Year: a third-year who graded highest with the students she taught. The petition to make peer teaching count for real credit reached the curriculum committee with 500 signatures.",
        "![Small-group revision in full flow](https://picsum.photos/seed/hl-scom-1/1200/900)",
      ],
    },
    {
      id: "hl-2026-scorp-humanity-trucks",
      category: "campus",
      tag: "Relief & Solidarity",
      title: "Humanity Trucks moved 5,000 kg of relief",
      date: "Dec 2026",
      location: "Two priority districts",
      committee: "scorp",
      summary: "A student-run winter collection delivered blankets, warm clothes and medicines to two hard-hit districts — with an audited list to match.",
      about: [
        "In midwinter, blankets are the difference between a room and a crime of indifference. Students ran a coordinated collection — blankets, warm clothes, simple medicines — and moved the convoy to registered sites over two days.",
        "The convoy cleared five tonnes of relief goods, every item logged against a published, audited list. The community's trust was the real cargo, and the run has already been pencilled in bigger for next winter.",
        "![Loading the convoy at dawn](https://picsum.photos/seed/hl-scorp-1/1200/900)",
        "![Distribution at a community site](https://picsum.photos/seed/hl-scorp-2/1200/900)",
      ],
    },
    {
      id: "hl-2026-natl-best-lc-award",
      category: "win",
      tag: "Recognition",
      title: "Best Local Committee — National Awards",
      date: "Dec 2026",
      location: "Islamabad, Pakistan",
      committee: "",
      summary: "The council was named Best Local Committee at the national assembly — the first time KMC has taken the title.",
      about: [
        "When they called the name at the national assembly, the KMC block needed a second to react. Best Local Committee is voted on by every other council in the country — a peer-graded verdict on the year we actually had.",
        "The award now hangs in the council room next to a much older one, and everyone agrees the gap between the two is the point: a local council that grew up, one project at a time.",
        "![The award held up at the assembly stage](https://picsum.photos/seed/hl-win-1/1200/900)",
      ],
    },
  ],

  // The trophy cabinet — achievements & awards page.
  awards: [
    /* ---------- Officer of the Year ---------- */
    {
      id: "aw-2026-officer-of-year",
      category: "officer",
      title: "Officer of the Year",
      awardee: "Mahnoor Khan",
      role: "Local Officer — SCOPH",
      year: "2026",
      location: "KMC Campus, Peshawar",
      source: "Council-wide vote",
      medal: "gold",
      summary: "The officer whose year left the biggest dent — voted by the members who watched her run Screening Saturday after Saturday.",
      about: [
        "The Officer of the Year is not chosen by the board. It is voted by the members — the students who showed up to a project and found her already there, clipboard in hand, calm as anything.",
        "This year the vote went to Mahnoor Khan. As Local Officer of SCOPH she turned one idea — screen a block, refer a block — into a monthly habit that crossed two thousand neighbours by December, trained a volunteer bench that runs itself, and never once let the paperwork win.",
        "![Mahnoor at a screening camp](https://picsum.photos/seed/aw-officer-1/1200/900)",
        "![Handing a results card to a resident](https://picsum.photos/seed/aw-officer-2/1200/900)",
      ],
      featured: true,
      sort_order: 0,
    },
    {
      id: "aw-2026-officer-runner-up",
      category: "officer",
      title: "Officer of the Year — Runner Up",
      awardee: "Bilal Shah",
      role: "Local Officer — SCOPE",
      year: "2026",
      location: "KMC Campus, Peshawar",
      source: "Council-wide vote",
      medal: "silver",
      summary: "Ran the council's biggest outbound cohort ever — twenty-two students, twelve countries, zero panics.",
      about: [
        "Runner-up honours went to Bilal Shah, the SCOPE officer who matched twenty-two students to rotations in twelve countries — and then sat by a phone at 3 a.m. for every one of them who landed somewhere unfamiliar.",
        "The pre-departure bootcamp ran twice to fit the demand, and every returning student got a debrief that made the next cohort a step ahead. Exchanges, he will tell you, are just a very large version of showing up.",
        "![The outbound cohort's group call](https://picsum.photos/seed/aw-officer-runnerup-1/1200/900)",
      ],
      featured: false,
      sort_order: 1,
    },
    {
      id: "aw-2026-peer-tutor-of-year",
      category: "officer",
      title: "Peer Tutor of the Year",
      awardee: "Hira Babar",
      role: "Peer Teaching Series — SCOME",
      year: "2026",
      location: "KMC Campus, Peshawar",
      source: "Student evaluations",
      medal: "bronze",
      summary: "The tutor the students graded highest — the fastest teaching format in medicine, crowned at the end-of-year ceremony.",
      about: [
        "Every week for a term, Hira stood in front of a small group of juniors and made anatomy make sense the way only someone who just survived the exam can. Her sessions scored higher than any tutor in the series' first year.",
        "The crown is a small trophy and a loud memory. The series' petition to make peer teaching count for real credit reached the curriculum committee with 500 signatures — and her name led the file.",
        "![Small-group revision in full flow](https://picsum.photos/seed/aw-tutor-1/1200/900)",
      ],
      featured: false,
      sort_order: 2,
    },

    /* ---------- Best Project ---------- */
    {
      id: "aw-2026-best-project-srh-week",
      category: "project",
      title: "Best Project — SRH Week",
      awardee: "SCORA",
      role: "Sexual & Reproductive Health Week",
      year: "2026",
      location: "KMC Campus, Peshawar",
      source: "Project of the year vote",
      medal: "gold",
      summary: "A thousand students, six hundred information kits, one very full locked box of anonymous questions.",
      about: [
        "For one week the taboos opened like a clinic door. SCORA turned the campus into a loud, warm, myth-busting marketplace — nurse-led talks students actually stayed for, a wall of answers to questions nobody ever asks in class, and a night screening for those who couldn't be on campus.",
        "The numbers did the arguing: more than a thousand students touched the week, all six hundred SRH information kits walked out free, and the anonymous question box took the team a week to read out because nobody expected that many.",
        "![SRH awareness booth on campus](https://picsum.photos/seed/aw-project-srh-1/1200/900)",
        "![Students at the myth-busting wall](https://picsum.photos/seed/aw-project-srh-2/1200/900)",
      ],
      featured: true,
      sort_order: 3,
    },
    {
      id: "aw-2026-best-project-screening",
      category: "project",
      title: "Best Project — Screening Saturdays",
      awardee: "SCOPH",
      role: "Community Health Screening Programme",
      year: "2026",
      location: "Racecourse Road, Peshawar",
      source: "Project of the year vote",
      medal: "silver",
      summary: "One Saturday a month, a whole block screened — and by year's end, two thousand neighbours had a number and a plan.",
      about: [
        "The most durable project the council runs is also the simplest: pack a bag, stand outside a school or mosque, and screen whoever walks up. Blood pressure, blood sugar, and a calm conversation with a student trained to refer.",
        "It won silver in the council's own vote because it never needs a stage — it just needs a Saturday. Two thousand people walked away with a card showing what normal looks like for their age and where to go if the number is red.",
        "![Screening camp at a community centre](https://picsum.photos/seed/aw-project-screen-1/1200/900)",
      ],
      featured: false,
      sort_order: 4,
    },
    {
      id: "aw-2026-best-project-humanity",
      category: "project",
      title: "Best Project — Humanity Trucks",
      awardee: "SCORP",
      role: "Winter Relief Collection",
      year: "2026",
      location: "Two priority districts",
      source: "Project of the year vote",
      medal: "bronze",
      summary: "Five tonnes of blankets and medicines moved in midwinter — every item logged, every receipt published.",
      about: [
        "In midwinter, blankets are the difference between a room and a crime of indifference. The convoy the council built cleared five tonnes of relief goods — blankets, warm clothes, simple medicines — to registered sites in two hard-hit districts.",
        "The trust was the real cargo. Every item was logged against a published, audited list, and the district office that once watched a student convoy with folded arms now asks the council for the plan first.",
        "![Loading the convoy at dawn](https://picsum.photos/seed/aw-project-trucks-1/1200/900)",
      ],
      featured: false,
      sort_order: 5,
    },

    /* ---------- Research Publications ---------- */
    {
      id: "aw-2026-pub-dengue",
      category: "research",
      title: "Seasonal trends of dengue at a Peshawar tertiary hospital, 2021–2025",
      awardee: "Raza, A.; Khan, M.; Yousaf, S.; et al. — KMC × IFMSA SCORE",
      role: "Accepted original research",
      year: "2026",
      source: "Journal of the Pakistan Medical Association",
      summary: "A five-year case series built on the question SCORP asked first: where do outbreaks actually start?",
      about: [
        "This paper started as a SCORE mentorship project in a KMC corridor and ended as an accepted submission to the Journal of the Pakistan Medical Association — a five-year retrospective of dengue admissions that maps seasonality to the exact neighbourhoods SCOPH's standing-water audits flagged.",
        "It is the first of the year's abstracts, but it will not be the last: the abstract clinic exists to make a habit of this.",
      ],
      link: "https://doi.org/10.5555/jpma.2026.01234",
      featured: false,
      sort_order: 6,
    },
    {
      id: "aw-2026-pub-peer-teaching",
      category: "research",
      title: "Peer-led versus faculty-led revision classes in undergraduate anatomy",
      awardee: "Babar, H.; Qureshi, H.; et al. — SCOME",
      role: "Accepted short report",
      year: "2026",
      source: "Medical Education Online",
      summary: "A small, honest comparison — with numbers — of the fastest teaching format in medicine.",
      about: [
        "SCOME kept saying peer teaching works because the students grading it said so. This short report made the claim testable: twenty matched sessions, identical content, one measurable outcome.",
        "Accepted by Medical Education Online, it is the series' proof-of-work — and the Tutor Academy now uses it as its opening reading.",
      ],
      link: "https://doi.org/10.5555/meo.2026.02345",
      featured: false,
      sort_order: 7,
    },
    {
      id: "aw-2026-pub-screening",
      category: "research",
      title: "Community-based hypertension screening in peri-urban Peshawar",
      awardee: "Yousafzai, S.; Noor, F.; et al. — SCOPH",
      role: "Accepted abstract",
      year: "2026",
      source: "Public Health in Practice",
      summary: "What two thousand Screening Saturday readings actually said about access to diagnosis.",
      about: [
        "Every Saturday the council screens a block; every patient gets a card. This abstract finally asks what two thousand of those cards mean — who got found out, who fell through the referral chain, and what a screening programme has to do to be a health system.",
        "It is the research arm of a project that never intended to have one.",
      ],
      link: "https://doi.org/10.5555/phip.2026.03456",
      featured: false,
      sort_order: 8,
    },

    /* ---------- International Recognition ---------- */
    {
      id: "aw-2026-ga-national-teams",
      category: "international",
      title: "Two national team seats — IFMSA March Meeting",
      awardee: "KMC delegates",
      role: "IFMSA General Assembly",
      year: "2026",
      location: "Cape Town, South Africa",
      source: "IFMSA General Assembly",
      medal: "gold",
      summary: "Six delegates, hand-written proposals, and two seats in IFMSA-Pakistan's national teams for the year ahead.",
      about: [
        "For nine days in March the whole movement met in Cape Town, and our six delegates carried Peshawar into the plenary — a workshop on peer-led education, a very patient poster about Screening Saturdays, and a vote or two that went our way.",
        "They came home with the real prize: two standing committees awarded seats in IFMSA-Pakistan's national teams, a direct line from a KMC hostel room to the rooms where the federation's health agenda is written.",
        "![Plenary hall at the General Assembly](https://picsum.photos/seed/aw-ga-1/1200/900)",
        "![KMC delegates at the closing ceremony](https://picsum.photos/seed/aw-ga-2/1200/900)",
      ],
      featured: true,
      sort_order: 9,
    },
    {
      id: "aw-2026-ga-workshop",
      category: "international",
      title: "Workshop selected for the March Meeting",
      awardee: "KMC delegation",
      role: "IFMSA General Assembly",
      year: "2026",
      location: "Cape Town, South Africa",
      source: "IFMSA General Assembly",
      summary: "The workshop on peer-led medical education that got picked — and ran twice because the room filled.",
      about: [
        "From thousands of submissions, the council's session on peer-led medical education was selected for the March Meeting programme — and ran twice after the first room filled past the seats.",
        "For the two students who designed it, the workshop was the whole point of the trip: not to attend the conference, but to teach one.",
        "![Workshop in session in Cape Town](https://picsum.photos/seed/aw-ga-ws-1/1200/900)",
      ],
      featured: false,
      sort_order: 10,
    },
    {
      id: "aw-2026-ga-delegation",
      category: "international",
      title: "Largest delegation on record",
      awardee: "KMC council",
      role: "National General Assembly",
      year: "2026",
      location: "Islamabad, Pakistan",
      source: "National General Assembly",
      summary: "The full executive plus every Local Officer — the biggest bench the council has ever sent to the capital.",
      about: [
        "The National General Assembly is where every local council in Pakistan sets the year ahead, and KMC sent its biggest delegation on record — the full executive and the Local Officers of all six standing committees.",
        "Two members came home with national team roles. The other twenty came home with the memory of a council that finally travels like it talks.",
        "![Delegation photo outside the assembly hall](https://picsum.photos/seed/aw-ga-del-1/1200/900)",
      ],
      featured: false,
      sort_order: 11,
    },

    /* ---------- National Partnerships ---------- */
    {
      id: "aw-2026-mou-dho-khyber",
      category: "national",
      title: "Memorandum of Understanding — District Health Office, Khyber",
      awardee: "District Health Office, Khyber",
      role: "Screening & relief partnership",
      year: "2026",
      location: "Khyber, Pakistan",
      source: "District Health Office",
      summary: "The district that once watched a student convoy with folded arms now plans relief with the council at the table.",
      about: [
        "Five years ago the council was a convoy of students with a clipboard. Today it signs MoUs. The first came from the district that saw the Humanity Trucks' audited lists — and decided the students could be trusted with a plan.",
        "Under the agreement, Screening Saturdays extend into the district's outreach roster and winter relief is co-planned, not improvised.",
      ],
      link: "",
      featured: false,
      sort_order: 12,
    },
    {
      id: "aw-2026-mou-pma-kpk",
      category: "national",
      title: "Partnership — Pakistan Medical Association (KPK)",
      awardee: "Pakistan Medical Association, KPK",
      role: "Advocacy & training partner",
      year: "2026",
      location: "Khyber Pakhtunkhwa",
      source: "Pakistan Medical Association",
      summary: "A formal seat at the table for student voices in medical education and public health advocacy.",
      about: [
        "The Pakistan Medical Association's Khyber Pakhtunkhwa branch opened its chapter to student delegates — a formal role for the council in advocacy, training weekends and the association's public-health calendar.",
        "The partnership makes the federation's local council an institutional voice, not just a campus club.",
      ],
      link: "",
      featured: false,
      sort_order: 13,
    },
    {
      id: "aw-2026-red-crescent-kpk",
      category: "national",
      title: "Partnership — Pakistan Red Crescent, KPK",
      awardee: "Pakistan Red Crescent, KPK",
      role: "Relief & first-aid partner",
      year: "2025",
      location: "Khyber Pakhtunkhwa",
      source: "Pakistan Red Crescent",
      summary: "The humanitarian arm behind Humanity Trucks — training, logistics and a standing lane for student relief.",
      about: [
        "Long before the five-tonne convoy, the council's relief work found a professional shoulder: Pakistan Red Crescent's KPK chapter provides first-aid training, logistics advice and a standing lane for student collection drives.",
        "The partnership turns a single winter campaign into an annual, practiced routine.",
      ],
      link: "",
      featured: false,
      sort_order: 14,
    },
    {
      id: "aw-2026-kp-health-dept",
      category: "national",
      title: "Collaboration — Khyber Pakhtunkhwa Health Department",
      awardee: "Khyber Pakhtunkhwa Health Department",
      role: "Vaccination & public-health drives",
      year: "2026",
      location: "Peshawar, Pakistan",
      source: "KP Health Department",
      summary: "The department that brings the vaccines; the council that brings the queue, the questions and the myth-busting wall.",
      about: [
        "The campus vaccination drive works because both halves of the system show up: the health department brings the vaccines and the staff, the council brings the appointments, the volunteers and the wall that quietly dismantles vaccine folklore.",
        "What started as a one-week drive is now a standing collaboration on the department's seasonal calendar.",
      ],
      link: "",
      featured: false,
      sort_order: 15,
    },

    /* ---------- Community Impact ---------- */
    {
      id: "aw-2026-community-screenings",
      category: "community",
      title: "2,000+ neighbours screened",
      awardee: "Screening Saturdays",
      role: "Community health",
      year: "2026",
      location: "Peshawar, Pakistan",
      source: "Year-end report",
      medal: "gold",
      summary: "Two thousand blood pressures, two thousand blood sugars, and a card for every single person who needed one.",
      about: [
        "The year-end total crossed two thousand people screened at the monthly camps — a number that started as one Saturday and a folding table outside a school.",
        "No one was graded; everyone was counted. That is the whole point of the project, and the number says it better than any trophy.",
        "![Screening camp at a community centre](https://picsum.photos/seed/aw-community-screen-1/1200/900)",
      ],
      featured: false,
      sort_order: 16,
    },
    {
      id: "aw-2026-community-relief",
      category: "community",
      title: "5,000 kg of relief delivered",
      awardee: "Humanity Trucks",
      role: "Winter relief",
      year: "2026",
      location: "Two priority districts",
      source: "Audited delivery log",
      medal: "silver",
      summary: "Five tonnes of blankets, warm clothes and medicines — every item logged, every delivery confirmed.",
      about: [
        "Five tonnes sounds abstract until you stand in the cold it crossed. The convoy cleared 5,000 kg of relief goods to registered sites in two hard-hit districts, with an audited list published for anyone who wanted to check.",
        "The trust that survived the audit is the real metric, and it compounds every winter.",
        "![Distribution at a community site](https://picsum.photos/seed/aw-community-relief-1/1200/900)",
      ],
      featured: false,
      sort_order: 17,
    },
    {
      id: "aw-2026-community-srh",
      category: "community",
      title: "600 SRH information kits given away",
      awardee: "SRH Week",
      role: "Sexual & reproductive health",
      year: "2026",
      location: "KMC Campus, Peshawar",
      source: "SRH Week report",
      medal: "bronze",
      summary: "Six hundred kits, a thousand students, and one anonymous question box that took a week to read out.",
      about: [
        "Every kit that walked out of SRH Week carried information the school system had never once volunteered. By the end of the week all six hundred were gone — most of them into the hands of students who had never had a safe place to ask.",
        "The anonymous question box is the part that will not fit in a stat: it took the team a week to read out, and every answer is now published for next year's campus.",
        "![SRH awareness booth on campus](https://picsum.photos/seed/aw-community-srh-1/1200/900)",
      ],
      featured: false,
      sort_order: 18,
    },
  ],
};